name: Matrix Demo
on: push
jobs:
    build:
        # you can add to prevent other jobs from stopping -> continue-on-error: true 
        strategy:
            matrix:
                node-version: [16 ,18, 20]
                operating-system: [ubuntu-latest, windows-latest]
                include: 
                    - node-version: 22
                    - operating-system: ubuntu-latest
                exclue:
                    - node-version: 16
                    - operating-system: windows-latest
        runs-on: ${{ matrix.operating-system }}
        steps: 
            - name: Get code
              uses: actions/checkout@v4
            - name: install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build